// DO NOT EDIT. This file was automatically generated by `/tools/build-ls.ts`.
package localization

// Dictionary
type Dictionary struct {
	SiteName string `json:"_siteName"`
	ErrorOccurred string `json:"errorOccurred"`
	HelloWorld string `json:"helloWorld"`
	Home string `json:"home"`
	Language string `json:"language"`
	PPageNotFound string `json:"pPageNotFound"`
	ResourceNotFound string `json:"resourceNotFound"`
}
